services:
  kpress-app-todo-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3031:3031"
    depends_on:
      - kpress-db-todo

  kpress-db-todo:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"